name: "PuttingtheSEAInCode"
navbar:
  title: "HOME"
  left:
    - text: "Instructions"
      href: SEAInCodeRIntro.html
output_dir: "."
output:
  html_document:
    theme: jekyll-theme-slate
    highlight: textmate
#    include:
#      after_body: _footer.html